name: Android CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "android13" ]
  pull_request:
    branches: [ "android13" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    continue-on-error: true

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: build/outputs/apk/debug/*.apk
